### ISSUE TITLE
Rearrange start experience based on USB-only update?

### ISSUE THREAD

**Issue by Frijol** [tessel/t2-start#101]
Do we want any changes to the T2 start experience based on https://github.com/tessel/t2-cli/pull/595?

We have currently arranged the start experience to require people to get Tessel online before they update. In Tessel 1, updates happened on the same page as installation.

Moving update back to the first page
1. Creates a cleaner divide between "I am installing things" and "I am using the Tessel 2" (which also affords us more flexibility if e.g. we want to put module usage before Wifi usage)
2. Let us put Blinky earlier - a first success before Wifi connection or trying to get lists working
3. Makes the installation phase take longer
4. Rearranges a start experience that may already be familiar to people

The purpose of the first run is to create success as quickly as possible, so:
1. How confident are we that `t2 update` will be successful for people?
2. How confident are we about Wifi connection will be a success?
3. Do we need people to update in order for Blinky to work?

Any thoughts on the matter (@johnnyman727 @rwaldron @tcr @HipsterBrown @flaki in particular)?

**Comment by johnnyman727** [comment]
:+1: on this endeavor.

> How confident are we that t2 update will be successful for people?

95%. It works really well for me. I fixed some issues that were causing hanging for other people. My only concern would be an as-of-yet unfound bug in large transfers over USB that would cause the transfer to hang but that won't brick anything.

> How confident are we about Wifi connection will be a success?

98%. It works for most people. Some have weird router issues that we can't control.

> Do we need people to update in order for Blinky to work?

Nope.

**Comment by snollygolly** [comment]
Keep in mind that I'm a novice with the Tessel and I've only done these start steps one time.

> How confident are we that t2 update will be successful for people?

It totally worked for me, first time, no issues.  I will say that the update renamed my Tessel and that was slightly confusing.  I know that's slightly off topic, but I thought I'd mention it.

> How confident are we about Wifi connection will be a success?

Airport Extreme, 802.11g/n, WPA2, no issues getting it set up.

Personally, I found the flow of steps easy to follow, straightforward.  I don't think changing the order around is necessary.

**Comment by Frijol** [comment]
👍  thanks for the opinions!

@snollygolly oh, I forgot about the renaming issue - it's been around for a while: https://github.com/tessel/t2-cli/issues/252

**Comment by flaki** [comment]
I don't really feel a need for moving update closer to the start, but I'd be :+1: for moving blinky closer to the start, to feed the instant-gratification-monkey. :monkey: 

_(...for the same instant-gratification monkey, it'd be great to show a short demo right after the wi-fi setup, showing how to serve a simple HTML page from the T2 with a sole button that lets them blink/toggle the LED by opening "Bulbasaur" from their browser and clicking the button — but that's probably for a different issue... :) )_
