### ISSUE TITLE
Host all images on imgur

### ISSUE THREAD

**Issue by tcr** [tessel/t2-start#11]
All images are currently hosted in S3 which is a little less than ideal, especially for contribution sake.

Should we move these? Should we use an infinite image host like imgur? Should we hack Github to support our binary image habit?

**Comment by Frijol** [comment]
imgur is a weird precedent. Does anyone do that?

**Comment by tcr** [comment]
I've done it fairly regularly. Free, unlimited image hosting with direct linking and without apparent moderation. Not version controlled / archivable though, so not desirable.

**Comment by Frijol** [comment]
I created a TesselProject imgur account, if anyone needs the credentials pls let me know
