### ISSUE TITLE
install tabs are broken

### ISSUE THREAD

**Issue by Frijol** [tessel/t2-start#12]
these tabs:
![screen shot 2015-08-11 at 10 16 53 pm](https://cloud.githubusercontent.com/assets/454690/9216985/bcf7c510-4076-11e5-8e40-3199b5611cc6.png)

If you click on them, you get the div in the URL but the tab doesn't change

**Comment by Frijol** [comment]
Need to remove class "active" from whatever div is currently active and add it to the clicked-on div

**Comment by Frijol** [comment]
Looks like some of this is in javascripts>custom>install.js - @tcr is this something you were working on?

**Comment by flaki** [comment]
For some reason the `markdownify` filter insisted on putting `<p>` tags inside `dd` tags. Because the path to tabs is hardcode in the Foundation tab handling lib, I had to work around this.
