### ISSUE TITLE
Discussion: can we indicate that "t2 update" is optional?

### ISSUE THREAD

**Issue by rwaldron** [tessel/t2-start#132]
I just unboxed a brand new Tessel 2, TM-T2-07, walked through the entire start process _on Windows_ with 100% success (this included installing fresh t2-cli). I wanted to see what firmware was shipping on these -07 builds, so I did `t2 version` and here's the result:  

```
C:\Users\Rick\j5ik>t2 version
INFO Looking for your Tessel...
INFO Connected to j5.
INFO Tessel [j5] CLI version: 0.0.22
INFO Tessel [j5] Firmware version: 0.0.13
INFO Tessel [j5] Node version: 4.4.3
```

0.0.13 is actually the latest release of the firmware! I'd like to discuss adding steps in the start experience that expose the user to `t2 version` and let them decide if `t2 update` is necessary. I may be wrong about this, which is totally cool, but let's weigh it first and see what we come up with :)

**Comment by johnnyman727** [comment]
@rwaldron running `t2 update` with a Tessel that's already at the most recent version should just abort unless a `-f` flag is provided, right? It seems like the 10 seconds it takes to run the command is worth knowing everyone is up-to-date.

**Comment by Frijol** [comment]
It's also non-optional for most if not all existing Tessels when they ship. Original T2 shipments had such old firmware they couldn't run blinky. I'd say until we get a preponderance of updated-image Tessel 2s into the marketplace (i.e. more than the preordered ones), we should leave as required.
