### ISSUE TITLE
Must have git installed to download t2 cli

### ISSUE THREAD

**Issue by Frijol** [tessel/t2-start#136]
We should note this prerequisite

**Comment by HipsterBrown** [comment]
Why is it a prerequisite?

**Comment by johnnyman727** [comment]
I believe `npm` uses it to fetch npm [dependencies that have a git url listed as the source](https://github.com/tessel/t2-cli/blob/master/package.json#L66).

**Comment by HipsterBrown** [comment]
Makes sense. Thanks for clarifying! 👍

**Comment by dtex** [comment]
Why is there a special npmlog at all?

Sorry if this is a known thing already, just seems weird.

**Comment by rwaldron** [comment]
There wouldn't be if _anyone_ at npm would follow on this: https://github.com/npm/npmlog/pull/34 https://github.com/npm/npmlog/issues/31

> Sorry if this is a known thing already, just seems weird.

Yes. Please help me get the attention of someone at npm

**Comment by dtex** [comment]
@rwaldron I know you have strong feelings about not polluting the npm ecosystem and I don't disagree one bit, but in this case would it be worth it for T2 users to go ahead and publish your version? 

I know most early adopters will of course have git, but with people ordering the J5IK and T2's figuring into Nodebots Day there are going to be people who are not git users coming into our community.

The readme could be updated to read something along the lines of:

```
Don't use this package in your project! It's for the T2-CLI only. 

Use this instead: https://www.npmjs.com/package/npmlog

It's a temporary fork of npmlog and shouldn't even exist, but until our PR lands we've gotta do this.
```

Similar problem getting a merge here: https://github.com/npm/fstream/pull/16 Note the date that this PR was submitted

**Comment by dtex** [comment]
To be fair, it looks like some work is being done on the fstream PR.

**Comment by rwaldron** [comment]
@dtex yes, I think you're right. I will do exactly as you've suggested.

**Comment by rwaldron** [comment]
This can be closed, there is no git dep in the coming release

**Comment by HipsterBrown** [comment]
Closing this as fixed by @rwaldron with https://github.com/tessel/t2-cli/commit/ee98070bdc561c40d182a11a54dccb69a965944a

**Comment by rwaldron** [comment]
@HipsterBrown thank you!
