### ISSUE TITLE
Running example code throws exception

### ISSUE THREAD

**Issue by pstricker** [tessel/t2-start#151]
I've used the example code for camera.js and when I go to run the application I receive the attached exception in the terminal.

![image](https://cloud.githubusercontent.com/assets/3308247/19831778/904e86a4-9dcf-11e6-99f4-582e4e01c249.png)

**Comment by HipsterBrown** [comment]
@pstricker I ran into the same error with the docs code and saw that `mjpg_streamer`, a dependency of `tessel-av`, was already using [port 8080 by default](https://github.com/tessel/tessel-av#avcamera). I'll make an update to the docs to fix that issue. You can fix it in the meantime if you change the `port` variable to another number like 8000.

**Comment by pstricker** [comment]
@HipsterBrown That would do it! Thanks for your help.

**Comment by rwaldron** [comment]
Pass `port: XXXX` to the Camera constructor to set a custom port.

**Comment by rwaldron** [comment]
I believe the example in the docs predates the migration to mjpg_streamer
