### ISSUE TITLE
Make all the views Markdown

### ISSUE THREAD

**Issue by tcr** [tessel/t2-start#3]
Jade is used extensively in the rest of Tessel's web properties. Do we want to use that as a publishing mechanism too?

This would require a publish step before uploading new changes, which is a little less magic than gh-pages automatically publishing. OTOH, it's very straightforward. And HTML is hard to manually touch.

**Comment by Frijol** [comment]
Would this be Jade as opposed to Markdown? Trying to figure out how this fits together with https://github.com/tessel/t2-start/issues/2

**Comment by Frijol** [comment]
ping

**Comment by Frijol** [comment]
Based on our [recent SC meeting](https://github.com/tessel/project/blob/master/meetings/2015-06-23.md) let's try doing everything in Markdown (more easily accessible, pretty standard). Currently exploring how well that plays with the existing work.

**Comment by tcr** [comment]
This has been completed.
