### ISSUE TITLE
What should be in the T2 start experience?

### ISSUE THREAD

**Issue by Frijol** [tessel/t2-start#4]
Let's start this discussion.
- Hello world blinky
- Hello internet– connect & tweet
- Regular modules
- USB modules
- Module ports as pins?
- Page of community modules

**Comment by johnnyman727** [comment]
We should definitely show examples with multiple modules. That definitely messed up a bunch of people with Tessel 1.

I also suggest that we show users how to interact with really useful APIs like PubNub, Twilio, etc.

**Comment by Frijol** [comment]
Multiple modules at once. Yeah, good idea.

Also "how to run disconnected from your computer" tripped up a lot of people on T1. Though that can come much earlier in the T2 start experience, given how great pushing over wifi is.

+1 to the interacting with APIs idea – that's what I was envisioning with the Hello internet step. The only question is, how do we decide which APIs to show and which not to?

**Comment by johnnyman727** [comment]
> Also "how to run disconnected from your computer" tripped up a lot of people on T1

Agreed, we should really highlight wireless deployment with T2.

> how do we decide which APIs to show and which not to?

Perhaps we allow API providers to add examples via PRs to the website? We can start it off with a couple that are really useful and work well (Firebase, PubNub, etc.) and see who else is interested.

**Comment by Frijol** [comment]
That's what I'm worried about - it could explode & intimidate new users if we're not careful. A single example with a long list of "you can also try..." would be fine but "here are 1000 tutorials for different APIs that all do pretty much the same thing, try them all!" is less great

**Comment by johnnyman727** [comment]
Yeah, you're right that all the examples of how to use the hundreds of different IoT APIs don't really belong in a start experience. We can keep it down to three or so?

**Comment by Frijol** [comment]
Which brings us back to the start:

> The only question is, how do we decide which APIs to show and which not to?

**Comment by johnnyman727** [comment]
Since you've been heading it up, why don't you make an executive decision based on what most users try to do with Tessel and the ease of different APIs? IMO Firebase, Pubnub, and Twilio should be under consideration.
