### ISSUE TITLE
blinky example doesn't match t2 init

### ISSUE THREAD

**Issue by Frijol** [tessel/t2-start#53]
Out put from t2 init and the code paste on http://tessel.github.io/t2-start/blinky.html are different. Need to update the blinky code on http://tessel.github.io/t2-start/blinky.html to match `t2 init`

**Comment by Frijol** [comment]
or possibly change `t2 init` in CLI to match blinky instead

**Comment by johnnyman727** [comment]
We already have a PR. Will make a new release and merge that PR today.

https://github.com/tessel/t2-cli/pull/372
