### ISSUE TITLE
Add a section to show how access points work & what they're good for

### ISSUE THREAD

**Issue by Frijol** [tessel/t2-start#73]
Would be cool to showcase this new use case in the start experience. @HipsterBrown any thoughts on what this should include?

**Comment by HipsterBrown** [comment]
Along with documenting the new command line feature, we could create a tutorial for that goes through the following steps:
- create a new access point
- write a node program
  - starts a simple server
  - responds to any connection with 'Hello from Tessel'
- connect to the Tessel access point
- run the node program and connect to the server address

If we wanted to dig deeper, in a more advanced tutorial, we could respond to any server connection with a web app that allows users to trigger the various LEDs on Tessel.
