### ISSUE TITLE
Climate module docs use image of climate-si7005

### ISSUE THREAD

**Issue by jonathana** [tessel/t2-start#75]
http://tessel.github.io/t2-start/modules/climate.html has an image in step 3 of a si-7005, but the instructions reference a si-7020.  The image should probably be updated, and the open question is whether the si-7005 should even be mentioned.  I have one, which is why I noticed.

**Comment by Frijol** [comment]
oh, thanks! Good point. @sidwarkd do you happen to have a photo of the si-7020 version of the climate module?

**Comment by sidwarkd** [comment]
Sorry, I only have an si-7005.

**Comment by mittalshravika** [comment]
Hi, updated climate.md file with the image of climate si-7020 module in Step 3.

**Comment by Frijol** [comment]
resolved by @mittalshravika with https://github.com/tessel/t2-start/pull/164
