### ISSUE TITLE
"tessel list" does not return connections

### ISSUE THREAD

**Issue by corymickelson** [tessel/t2-start#90]
running t2 list can not find the tessel connected to same wifi network that the computer is connected over. Amber light is blinking which is supposed to mean it's connected. There is only a single wifi network at my location. Running t2 wifi -n {network} -p {password} returns: WIFI enabled, WIFI connected. SSID:{network name}, password: {password}, security: psk2. But then t2 list only shows the usb connection.

**Comment by johnnyman727** [comment]
Closing this in favor of your [other PR](https://github.com/tessel/t2-cli/issues/650). Thanks for reporting!
