### ISSUE TITLE
BLE instructions are old

### ISSUE THREAD

**Issue by johnnyman727** [tessel/t2-start#93]
They should no longer have a section about obtaining root and running `hciconfig`

**Comment by zshannon** [comment]
This section still needs to be present, and [PR#94](https://github.com/tessel/t2-start/issues/94) should be reverted. I just lost a lot of time debugging the ble module not powering on, and running the `hciconfig hci0 up` fixed it instantly.

```
INFO Tessel [Tessel-XXXXXXXXXXX] CLI version: 0.0.19
INFO Tessel [Tessel-XXXXXXXXXXX] Firmware version: 0.0.12
INFO Tessel [Tessel-XXXXXXXXXXX] Node version: 4.2.1
```

**Comment by johnnyman727** [comment]
@zshannon sorry to hear you had some difficulties. I wonder if perhaps the hotplug functionality is not available on some dongles? Can you paste a link to more info on your BLE dongle?

**Comment by zshannon** [comment]
@johnnyman727 I'm using this one [from Amazon](http://www.amazon.com/Plugable-Bluetooth-Adapter-Raspberry-Compatible/dp/B009ZIILLI) (I think it's the recommended one)

**Comment by zshannon** [comment]
@johnnyman727 after several more hours of debugging, the issue seems to have been `bluetoothd` competing to control the bluetooth connections. When I removed it from startup on the Tessel, bluetooth connections started working as expected (in `bleno`; using hotplugging control). Any clue where I should create a new issue about this?

**Comment by johnnyman727** [comment]
@zshannon if you could open an issue with details on how to reproduce on [`openwrt-tessel`](https://github.com/tessel/openwrt-tessel), that would be perfect. Thanks!

**Comment by rafaelcmrj** [comment]
same problem here. I had to go into ssh and power it on..
